# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = ENV['API_MAIL']
  config.secret_key = ENV['API_MAIL_SECRET']
  config.default_from = 'n.zhao31415@gmail.com'

end
